// commonMatchesAt - does the destination hold the same voice pack we do?
//
// This decides whether a ~28 MB copy is skipped, so the dangerous direction is
// a FALSE "identical": it skips the write silently and leaves the user believing
// their card is current. Most of the cases below exist to prove we do not take
// a shortcut that could produce one.
//
// The rule under test (2026-07-31): a cached claim about a filesystem we
// do not control may RAISE a question, never suppress one. So the marker file
// is never consulted for the decision, and the cheap file-count/byte signal is
// only ever trusted as a NEGATIVE.
'use strict';

const fs   = require('fs');
const os   = require('os');
const path = require('path');

const { commonMatchesAt, writeCommonReadme, readCommonMarkerAt } = require('../soundFontCommon');

const UUID = 'test-uuid-0001';
let failures = 0;

function mkTemp() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'jmt-common-match-'));
}

// Builds a userData tree holding one common, plus a separate destination root.
// `files` is { relPath: contents }.
function setup(libFiles, cardFiles, targetName = 'common') {
  const root     = mkTemp();
  const userData = path.join(root, 'userData');
  const dest     = path.join(root, 'card');
  const libDir   = path.join(userData, 'soundFonts', 'common', UUID, 'files');

  fs.mkdirSync(libDir, { recursive: true });
  fs.writeFileSync(
    path.join(userData, 'soundFonts', 'common', UUID, 'meta.json'),
    JSON.stringify({ schemaVersion: 1, uuid: UUID, name: 'Test_Voicepack', createdAt: '2026-06-19T00:00:00.000Z' }),
  );
  write(libDir, libFiles);

  if (cardFiles !== null) {
    const cardDir = path.join(dest, targetName);
    fs.mkdirSync(cardDir, { recursive: true });
    write(cardDir, cardFiles);
  }
  return { userData, dest, libDir, cardDir: path.join(dest, targetName) };
}

function write(root, files) {
  for (const [rel, body] of Object.entries(files)) {
    const abs = path.join(root, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, body);
  }
}

function check(label, actual, expected) {
  const ok = Object.entries(expected).every(([k, v]) => actual[k] === v);
  if (ok) { console.log('PASS ' + label); return; }
  failures++;
  console.log('FAIL ' + label);
  console.log('     expected ' + JSON.stringify(expected));
  console.log('     actual   ' + JSON.stringify(actual));
}

// The baseline pack both sides start from.
const PACK = {
  'mmain.wav':     'AAAA-main-audio',
  'mfont.wav':     'BBBB-font-audio',
  'voicepack.ini': 'voice_pack_version = 2\n',
  'sub/extra.wav': 'CCCC-nested',
};

// ── The identical cases ────────────────────────────────────────────────────

{
  const { userData, dest } = setup(PACK, PACK);
  check('byte-identical, neither side has a marker',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: true, identical: true });
}

{
  // The marker is ours and must be subtracted from the comparison, or every
  // card we have ever written would look different from the library.
  const { userData, dest, cardDir } = setup(PACK, PACK);
  writeCommonReadme(userData, UUID, cardDir);
  check('byte-identical, card carries our marker (subtracted)',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: true, identical: true });
}

{
  // The case that broke this, 2026-07-31: the marker was deleted by hand and the app then
  // demanded a keep-or-replace decision about a folder that had not changed.
  const { userData, dest, cardDir } = setup(PACK, PACK);
  writeCommonReadme(userData, UUID, cardDir);
  for (const f of fs.readdirSync(cardDir)) {
    if (f.toLowerCase().endsWith('.txt')) fs.unlinkSync(path.join(cardDir, f));
  }
  check('byte-identical, marker DELETED by hand',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: true, identical: true });
}

{
  // The load-bearing case. A marker states what we wrote LAST time. Here it is
  // deliberately lying about a pack that is in fact identical. If the answer
  // came from the marker this would come back not-identical.
  const { userData, dest, cardDir } = setup(PACK, PACK);
  fs.writeFileSync(path.join(cardDir, 'a_Something_Else.txt'),
    'Something_Else\r\n\r\nContent hash       : ' + 'f'.repeat(64) + '\r\n' +
    'Generated by JMT Studio 1.8.0. This file is ignored by ProffieOS.\r\n');
  check('STALE marker claiming a different hash is ignored',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: true, identical: true });
}

{
  // A card written by an SD backup, another tool, or a version of the app that
  // predates markers. No marker will ever appear, and it must still be
  // recognised rather than prompting on every single export forever.
  const { userData, dest } = setup(PACK, PACK);
  check('identical pack from a source that never wrote a marker',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: true, identical: true });
}

// ── The must-not-be-identical cases ────────────────────────────────────────

{
  // Same file count, same total bytes, different content. This is the case the
  // cheap signal CANNOT see, which is exactly why it may only gate into the
  // hash and never past it. A false pass here is the silent-stale-card bug.
  const swapped = Object.assign({}, PACK, { 'mmain.wav': 'ZZZZ-main-audio' });
  const { userData, dest } = setup(PACK, swapped);
  check('same size, different bytes -> caught by the hash, not the signal',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: true, identical: false, reason: 'hash' });
}

{
  const extra = Object.assign({}, PACK, { 'bonus.wav': 'DDDD-extra' });
  const { userData, dest } = setup(PACK, extra);
  check('card has an extra file',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: true, identical: false, reason: 'signals' });
}

{
  const missing = Object.assign({}, PACK);
  delete missing['mfont.wav'];
  const { userData, dest } = setup(PACK, missing);
  check('card is missing a file',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: true, identical: false, reason: 'signals' });
}

{
  // Only files WE generated get subtracted. Someone else's text file is real
  // content and a real difference.
  const withUserTxt = Object.assign({}, PACK, { 'my-notes.txt': 'do not delete this' });
  const { userData, dest } = setup(PACK, withUserTxt);
  check("a user's own .txt is content, not a marker",
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: true, identical: false, reason: 'signals' });
}

{
  // Marker detection is root-level only. A nested file that happens to contain
  // the same phrase is content and must not be silently dropped from the hash.
  const nested = Object.assign({}, PACK, { 'sub/readme.txt': 'Generated by JMT Studio 1.8.0.' });
  const { userData, dest } = setup(PACK, nested);
  check('nested txt quoting the marker phrase is still content',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: true, identical: false, reason: 'signals' });
}

// ── Absent / unreadable ────────────────────────────────────────────────────

{
  const { userData, dest } = setup(PACK, null);
  check('destination has no common folder at all',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: false, identical: false, reason: 'missing' });
}

{
  const { userData, dest } = setup(PACK, PACK);
  check('unknown uuid never reports identical',
    commonMatchesAt(userData, 'no-such-uuid', dest), { ok: true, exists: true, identical: false, reason: 'unreadable' });
}

{
  const r = commonMatchesAt('', UUID, '');
  check('missing arguments fail closed', r, { ok: false });
}

// ── A destination folder that is not called "common" ───────────────────────

{
  // The app now seeds non-default shared-folder names into configs, so the
  // compare has to be able to look somewhere other than "common".
  const { userData, dest } = setup(PACK, PACK, 'MC');
  check('honours a non-default target name',
    commonMatchesAt(userData, UUID, dest, 'MC'), { ok: true, exists: true, identical: true });
  check('and does not find it under the default name',
    commonMatchesAt(userData, UUID, dest), { ok: true, exists: false, reason: 'missing' });
}

// ── The marker's own contract ──────────────────────────────────────────────

function line(body, startsWith) {
  return (body.split(/\r?\n/).find(l => l.startsWith(startsWith)) || '').trim();
}

{
  const { userData, dest, cardDir } = setup(PACK, PACK);
  const r = writeCommonReadme(userData, UUID, cardDir);
  const body = fs.readFileSync(path.join(cardDir, r.fileName), 'utf8');
  const lines = body.split(/\r?\n/);

  check('filename says who wrote it and which pack',
    { name: r.fileName }, { name: 'a_JMT_Test_Voicepack.txt' });
  check('pack name is still line 1 (scannable, and what the reader parses)',
    { l: lines[0] }, { l: 'Test_Voicepack' });
  check('byline is line 2, above any fact about the pack',
    { has: /^Generated by JMT Studio.*not part of the voice pack\.$/.test(lines[1]) }, { has: true });
  check('no content hash is printed any more',
    { has: /Content hash/i.test(body) }, { has: false });
  check('version line carries the plain-English qualifier',
    { l: line(body, 'Voice pack version') }, { l: 'Voice pack version : 2  (what ProffieOS 8 expects)' });
  check('file count excludes the marker itself',
    { l: line(body, 'Files') }, { l: 'Files              : 4  (0.0 MB)' });
  check('the closing line says deleting it is safe',
    { has: /Deleting it is safe\./.test(body) }, { has: true });

  // The whole identity mechanism keys off this phrase. If a future wording edit
  // drops it, every exported card reads as different from the library forever,
  // silently — so the writer refuses rather than shipping it.
  check('the identifying phrase is present',
    { has: body.includes('Generated by JMT Studio') }, { has: true });

  const marker = readCommonMarkerAt(dest);
  check('reader recovers the pack name', { name: marker && marker.name }, { name: 'Test_Voicepack' });
  check('reader recovers the version past the qualifier', { v: marker && marker.version }, { v: '2' });
}

{
  // A V1 pack is the case that actually hurts, so the card itself carries the
  // diagnosis rather than a bare number.
  const v1 = Object.assign({}, PACK, { 'voicepack.ini': 'voice_pack_version = 1\n' });
  const { userData, cardDir } = setup(v1, v1);
  const r = writeCommonReadme(userData, UUID, cardDir);
  const body = fs.readFileSync(path.join(cardDir, r.fileName), 'utf8');
  check('a V1 pack says why that matters',
    { l: line(body, 'Voice pack version') },
    { l: 'Voice pack version : 1  (ProffieOS 8 props usually require version 2)' });
}

{
  const noIni = Object.assign({}, PACK);
  delete noIni['voicepack.ini'];
  const { userData, cardDir } = setup(noIni, noIni);
  const r = writeCommonReadme(userData, UUID, cardDir);
  const body = fs.readFileSync(path.join(cardDir, r.fileName), 'utf8');
  check('a pack with no ini says so rather than guessing',
    { l: line(body, 'Voice pack version') },
    { l: 'Voice pack version : not stated (no voicepack.ini)' });
}

{
  // Old-format marker (a_<Name>.txt) must be cleaned up on the next export, or
  // the card carries two markers and the file count is wrong.
  const { userData, dest, cardDir } = setup(PACK, PACK);
  fs.writeFileSync(path.join(cardDir, 'a_Test_Voicepack.txt'),
    'Test_Voicepack\r\n\r\nGenerated by JMT Studio 1.7.1. This file is ignored by ProffieOS.\r\n');
  writeCommonReadme(userData, UUID, cardDir);
  const txts = fs.readdirSync(cardDir).filter(f => f.toLowerCase().endsWith('.txt'));
  check('an old-format marker is replaced, not accumulated',
    { n: txts.length, only: txts[0] }, { n: 1, only: 'a_JMT_Test_Voicepack.txt' });
  check('and the card still compares as identical afterwards',
    commonMatchesAt(userData, UUID, dest), { ok: true, identical: true });
}

{
  // The library copy must never gain a marker. Previously destDir defaulted to
  // the library's files/ dir, which is the one call that would undo the design.
  const { userData } = setup(PACK, PACK);
  check('writing without a destination is refused',
    writeCommonReadme(userData, UUID, ''), { ok: false });
}

{
  // A non-default shared folder name has to be reflected in the instruction
  // line, or the file tells the user to type the wrong thing.
  const { userData, cardDir } = setup(PACK, PACK, 'MC');
  const r = writeCommonReadme(userData, UUID, cardDir);
  const body = fs.readFileSync(path.join(cardDir, r.fileName), 'utf8');
  check('the instruction names the actual folder',
    { has: body.includes('adding ";MC" to their font path') }, { has: true });
}

// The manifest must not be able to declare a stale card current, and a hand
// edit must cost only the file that changed.
{
  const { userData, dest, cardDir } = setup(PACK, PACK);
  const first = commonMatchesAt(userData, UUID, dest);
  check('identical, and the first pass reads the card', first, { ok: true, identical: true });

  const second = commonMatchesAt(userData, UUID, dest);
  check('the second pass still says identical', second, { ok: true, identical: true });

  // Now edit the card behind the manifest's back.
  const f = path.join(cardDir, 'mmain.wav');
  fs.writeFileSync(f, 'ZZZZ-swapped');
  const future = (Date.now() + 60000) / 1000;
  fs.utimesSync(f, future, future);
  check('editing the card is caught rather than reused',
    commonMatchesAt(userData, UUID, dest), { ok: true, identical: false });
}

console.log('');
if (failures) {
  console.error(failures + ' common-match test(s) failed');
  process.exit(1);
}
console.log('all common-match tests passed');
